/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#6f2512',
        'on-primary': '#ffffff',
        'primary-container': '#8e3b26',
        'on-primary-container': '#ffb9a8',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a2',
        'on-primary-fixed': '#3c0700',
        'on-primary-fixed-variant': '#7c2d1a',
        'inverse-primary': '#ffb4a2',
        'secondary': '#4c56af',
        'on-secondary': '#ffffff',
        'secondary-container': '#959efd',
        'on-secondary-container': '#27308a',
        'secondary-fixed': '#e0e0ff',
        'secondary-fixed-dim': '#bdc2ff',
        'on-secondary-fixed': '#000767',
        'on-secondary-fixed-variant': '#343d96',
        'tertiary': '#523a00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6d5010',
        'on-tertiary-container': '#ecc479',
        'tertiary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#e9c176',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4201',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fbf9f4',
        'on-background': '#1b1c19',
        'surface': '#fbf9f4',
        'on-surface': '#1b1c19',
        'surface-dim': '#dbdad5',
        'surface-bright': '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'surface-variant': '#e4e2dd',
        'on-surface-variant': '#55423e',
        'outline': '#88726d',
        'outline-variant': '#dbc1ba',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        'surface-tint': '#9a442e',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'serif'],
        'sans': ['"Be Vietnam Pro"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'gutter': '16px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'base': '8px',
        'container-padding-mobile': '16px',
        'container-padding-desktop': '40px',
      },
    },
  },
  plugins: [],
};
